// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/bingfood-client-micro/app/user/service/internal/biz/user"
	"github.com/go-kratos/bingfood-client-micro/app/user/service/internal/conf"
	"github.com/go-kratos/bingfood-client-micro/app/user/service/internal/data"
	"github.com/go-kratos/bingfood-client-micro/app/user/service/internal/server"
	"github.com/go-kratos/bingfood-client-micro/app/user/service/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, jwt *conf.JWT, logger log.Logger, registry *conf.Registry) (*kratos.App, func(), error) {
	db := data.NewDB(confData)
	dataData, cleanup, err := data.NewData(confData, logger, db)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData, logger)
	userUsecase := user.NewUserUsecase(userRepo, logger)
	bingfoodServiceImpl := service.NewBingfoodService(userUsecase)
	httpServer := server.NewHTTPServer(confServer, jwt, bingfoodServiceImpl, logger)
	grpcServer := server.NewGRPCServer(confServer, bingfoodServiceImpl, logger)
	registrar := server.NewRegistrar(registry)
	app := newApp(logger, httpServer, grpcServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
