version: '3'
services:
#  web-shop:
#    image: go-kratos/beer-web-shop:0.1.0
#    ports:
#      - 80:80
#  web-admin:
#    image: go-kratos/beer-web-admin:0.1.0
#    ports:
#      - 81:81
  user-service:
    image: 1.14.163.5:5000/user_service:v1
    hostname: user-service
    depends_on:
      - user-db
#    command: ["sh","wait-for-it.sh", "user-db:3306", "--", "./server" ]
    command: ["./server"]

  user-db:
    image: mysql:5.7
    hostname: user-db
    container_name: mysql-5.7-user-db
    privileged: true
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASS: 1234
      TZ: Asia/Shanghai
    command:
      --wait_timeout=31536000
      --interactive_timeout=31536000
      --max_connections=1000
      --default-authentication-plugin=mysql_native_password
    volumes:
      #映射mysql的数据目录到宿主机，保存数据
      - "/app/mysql/data:/var/lib/mysql"
      #根据宿主机下的配置文件创建容器
      - "/app/mysql/conf/my.cnf:/etc/mysql/my.cnf"

#  catalog-service:
#    image: go-kratos/beer-catalog-service:0.1.0
#    hostname: catalog-service
#    depends_on:
#      - catalog-db
#  catalog-db:
#    image: mysql:8
#    hostname: catalog-db
#    environment:
#      MYSQL_ROOT_PASSWORD: dangerous
#  cart-service:
#    image: go-kratos/beer-cart-service:0.1.0
#    hostname: cart-service
#    depends_on:
#      - cart-db
#  cart-db:
#    image: mongo:4
#    hostname: cart-db
#    environment:
#      MONGO_INITDB_ROOT_PASSWORD: dangerous
#  order-service:
#    image: go-kratos/beer-cart-service:0.1.0
#    hostname: order-service
#    depends_on:
#      - order-db
#  order-db:
#    image: mysql:8
#    hostname: order-db
#    environment:
#      MYSQL_ROOT_PASSWORD: dangerous
#  payment-service:
#    image: go-kratos/beer-payment-service:0.1.0
#    hostname: cart-service
#  zookeeper:
#    image: docker.io/bitnami/zookeeper:3.7
#    ports:
#      - 2181:2181
#    environment:
#      - ALLOW_ANONYMOUS_LOGIN=yes
#  kafka:
#    image: docker.io/bitnami/kafka:2
#    ports:
#      - 9092:9092
#    environment:
#      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
#      - ALLOW_PLAINTEXT_LISTENER=yes
#    depends_on:
#      - zookeeper