version: '3'
services:

  #  bingfood-service:
  #    image: 1.14.163.5:5000/bingfood/bingfood-bingfood-service:0.1.0
  #    container_name: bingfood-service
  #    hostname: bingfood-service
  #    depends_on:
  #      - bingfood-db
  #      - etcd
  #    #    command: ["sh","wait-for-it.sh", "user-db:3306", "--", "./configs" ]
  #    command: [ "./cmd" ]

  bingfood-db:
    image: mysql:5.7
    hostname: bingfood-db
    container_name: mysql-5.7-bingfood-db
    privileged: true
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASS: 1234
      TZ: Asia/Shanghai
    command:
      --wait_timeout=31536000
      --interactive_timeout=31536000
      --max_connections=1000
      --default-authentication-plugin=mysql_native_password
    volumes:
      #映射mysql的数据目录到宿主机，保存数据
      - "/app/mysql-bingfood/data:/var/lib/mysql"
      #根据宿主机下的配置文件创建容器
      - "/app/mysql-bingfood/conf/my.cnf:/etc/mysql/my.cnf"


  #  user-service:
  #    image: 1.14.163.5:5000/bingfood/bingfood-user-service:0.1.0
  #    container_name: bingfood-user-service
  #    hostname: user-service
  #    depends_on:
  #      - user-db
  #      - etcd
  #    #    command: ["sh","wait-for-it.sh", "user-db:3306", "--", "./configs" ]
  #    command: [ "./cmd" ]

  user-db:
    image: mysql:5.7
    hostname: user-db
    container_name: mysql-5.7-user-db
    privileged: true
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASS: 1234
      TZ: Asia/Shanghai
    command:
      --wait_timeout=31536000
      --interactive_timeout=31536000
      --max_connections=1000
      --default-authentication-plugin=mysql_native_password
    volumes:
      #映射mysql的数据目录到宿主机，保存数据
      - "/app/mysql-user/data:/var/lib/mysql"
      #根据宿主机下的配置文件创建容器
      - "/app/mysql-user/conf/my.cnf:/etc/mysql/my.cnf"

  #  order-service:
  #    image: 1.14.163.5:5000/bingfood/bingfood-user-service:0.1.0
  #    container_name: bingfood-order-service
  #    hostname: order-service
  #    depends_on:
  #      - order-db
  #      - etcd
  #    #    command: ["sh","wait-for-it.sh", "user-db:3306", "--", "./configs" ]
  #    command: [ "./cmd" ]

  order-db:
    image: mysql:5.7
    hostname: order-db
    container_name: mysql-5.7-order-db
    privileged: true
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASS: 1234
      TZ: Asia/Shanghai
    command:
      --wait_timeout=31536000
      --interactive_timeout=31536000
      --max_connections=1000
      --default-authentication-plugin=mysql_native_password
    volumes:
      #映射mysql的数据目录到宿主机，保存数据
      - "/app/mysql-order/data:/var/lib/mysql"
      #根据宿主机下的配置文件创建容器
      - "/app/mysql-order/conf/my.cnf:/etc/mysql/my.cnf"


  #  cart-service:
  #    image: 1.14.163.5:5000/bingfood/bingfood-cart-service:0.1.0
  #    container_name: bingfood-cart-service
  #    hostname: cart-service
  #    depends_on:
  #      - cart-db
  #      - etcd
  #    #    command: ["sh","wait-for-it.sh", "user-db:3306", "--", "./configs" ]
  #    command: [ "./cmd" ]

  cart-db:
    image: mysql:5.7
    hostname: cart-db
    container_name: mysql-5.7-cart-db
    privileged: true
    restart: always
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASS: 1234
      TZ: Asia/Shanghai
    command:
      --wait_timeout=31536000
      --interactive_timeout=31536000
      --max_connections=1000
      --default-authentication-plugin=mysql_native_password
    volumes:
      #映射mysql的数据目录到宿主机，保存数据
      - "/app/mysql-cart/data:/var/lib/mysql"
      #根据宿主机下的配置文件创建容器
      - "/app/mysql-cart/conf/my.cnf:/etc/mysql/my.cnf"


  prod-db:
    image: mysql:5.7
    hostname: prod-db
    container_name: mysql-5.7-prod-db
    privileged: true
    restart: always
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASS: 1234
      TZ: Asia/Shanghai
    command:
      --wait_timeout=31536000
      --interactive_timeout=31536000
      --max_connections=1000
      --default-authentication-plugin=mysql_native_password
    volumes:
      #映射mysql的数据目录到宿主机，保存数据
      - "/app/mysql-prod/data:/var/lib/mysql"
      #根据宿主机下的配置文件创建容器
      - "/app/mysql-prod/conf/my.cnf:/etc/mysql/my.cnf"



  etcd:
    image: bitnami/etcd:3
    hostname: etcd
    container_name: etcd-service
    #    deploy:
    #      replicas: 1
    #      restart_policy:
    #        condition: on-failure
    # ports:
    #   - "2379:2379"
    #   - "2380:2380"
    #   - "4001:4001"
    #   - "7001:7001"
    privileged: true
    volumes:
      - "/app/etcd/data:/bitnami/etcd/data"
    environment:
      - "ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379"
      - "ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379"
      #集群节点之间监听2380
      - "ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380"
      - "ETCD_INITIAL_ADVERTISE_PEER_URLS=http://0.0.0.0:2380"
      #参数指不用密码可以连接
      - "ALLOW_NONE_AUTHENTICATION=yes"
      - "ETCD_INITIAL_CLUSTER=node1=http://0.0.0.0:2380"
      - "ETCD_NAME=node1"
      - "ETCD_DATA_DIR=/opt/bitnami/etcd/data"
    ports:
      - 2379:2379
      - 2380:2380
