server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s

data:
  database:
    dsn: root:1234@tcp(1.14.163.5:3306)/bingFood?charset=utf8mb4&parseTime=True&loc=Local
  redis:
    addr: 1.14.163.5:6379
    read_timeout: 0.2s
    write_timeout: 0.2s

jwt:
  api_secret_key: bingfood
  service_secret_key: bingguWang_bingfood