// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.1
// source: user/v1/user.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BingfoodServiceClient is the client API for BingfoodService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BingfoodServiceClient interface {
	LoginOrRegister(ctx context.Context, in *UserLoginOrRegisterRequest, opts ...grpc.CallOption) (*UserLoginOrRegisterReply, error)
	SetUserPassword(ctx context.Context, in *SetUserPasswordRequest, opts ...grpc.CallOption) (*SetUserPasswordReply, error)
}

type bingfoodServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBingfoodServiceClient(cc grpc.ClientConnInterface) BingfoodServiceClient {
	return &bingfoodServiceClient{cc}
}

func (c *bingfoodServiceClient) LoginOrRegister(ctx context.Context, in *UserLoginOrRegisterRequest, opts ...grpc.CallOption) (*UserLoginOrRegisterReply, error) {
	out := new(UserLoginOrRegisterReply)
	err := c.cc.Invoke(ctx, "/user.v1.BingfoodService/LoginOrRegister", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bingfoodServiceClient) SetUserPassword(ctx context.Context, in *SetUserPasswordRequest, opts ...grpc.CallOption) (*SetUserPasswordReply, error) {
	out := new(SetUserPasswordReply)
	err := c.cc.Invoke(ctx, "/user.v1.BingfoodService/SetUserPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BingfoodServiceServer is the server API for BingfoodService service.
// All implementations must embed UnimplementedBingfoodServiceServer
// for forward compatibility
type BingfoodServiceServer interface {
	LoginOrRegister(context.Context, *UserLoginOrRegisterRequest) (*UserLoginOrRegisterReply, error)
	SetUserPassword(context.Context, *SetUserPasswordRequest) (*SetUserPasswordReply, error)
	mustEmbedUnimplementedBingfoodServiceServer()
}

// UnimplementedBingfoodServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBingfoodServiceServer struct {
}

func (UnimplementedBingfoodServiceServer) LoginOrRegister(context.Context, *UserLoginOrRegisterRequest) (*UserLoginOrRegisterReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginOrRegister not implemented")
}
func (UnimplementedBingfoodServiceServer) SetUserPassword(context.Context, *SetUserPasswordRequest) (*SetUserPasswordReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetUserPassword not implemented")
}
func (UnimplementedBingfoodServiceServer) mustEmbedUnimplementedBingfoodServiceServer() {}

// UnsafeBingfoodServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BingfoodServiceServer will
// result in compilation errors.
type UnsafeBingfoodServiceServer interface {
	mustEmbedUnimplementedBingfoodServiceServer()
}

func RegisterBingfoodServiceServer(s grpc.ServiceRegistrar, srv BingfoodServiceServer) {
	s.RegisterService(&BingfoodService_ServiceDesc, srv)
}

func _BingfoodService_LoginOrRegister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserLoginOrRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BingfoodServiceServer).LoginOrRegister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.v1.BingfoodService/LoginOrRegister",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BingfoodServiceServer).LoginOrRegister(ctx, req.(*UserLoginOrRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BingfoodService_SetUserPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetUserPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BingfoodServiceServer).SetUserPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.v1.BingfoodService/SetUserPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BingfoodServiceServer).SetUserPassword(ctx, req.(*SetUserPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BingfoodService_ServiceDesc is the grpc.ServiceDesc for BingfoodService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BingfoodService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.v1.BingfoodService",
	HandlerType: (*BingfoodServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoginOrRegister",
			Handler:    _BingfoodService_LoginOrRegister_Handler,
		},
		{
			MethodName: "SetUserPassword",
			Handler:    _BingfoodService_SetUserPassword_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user/v1/user.proto",
}
