// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// protoc-gen-go-http v2.3.1

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationBingfoodServiceOrderSettle = "/bingfood.service.v1.BingfoodService/OrderSettle"

type BingfoodServiceHTTPServer interface {
	OrderSettle(context.Context, *SettleOrderRequest) (*SettleOrderReply, error)
}

func RegisterBingfoodServiceHTTPServer(s *http.Server, srv BingfoodServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/order/settle", _BingfoodService_OrderSettle0_HTTP_Handler(srv))
}

func _BingfoodService_OrderSettle0_HTTP_Handler(srv BingfoodServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SettleOrderRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBingfoodServiceOrderSettle)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.OrderSettle(ctx, req.(*SettleOrderRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SettleOrderReply)
		return ctx.Result(200, reply)
	}
}

type BingfoodServiceHTTPClient interface {
	OrderSettle(ctx context.Context, req *SettleOrderRequest, opts ...http.CallOption) (rsp *SettleOrderReply, err error)
}

type BingfoodServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewBingfoodServiceHTTPClient(client *http.Client) BingfoodServiceHTTPClient {
	return &BingfoodServiceHTTPClientImpl{client}
}

func (c *BingfoodServiceHTTPClientImpl) OrderSettle(ctx context.Context, in *SettleOrderRequest, opts ...http.CallOption) (*SettleOrderReply, error) {
	var out SettleOrderReply
	pattern := "/order/settle"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationBingfoodServiceOrderSettle))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
